<a href="https://colab.research.google.com/github/mohitgoyal1409/machine_learning/blob/main/23_KNN_imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer , KNNImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [ ]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [ ]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [ ]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
X_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [ ]:
knn = KNNImputer(n_neighbors=3,weights='distance')

In [ ]:
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [ ]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

           Age  Pclass      Fare
0    40.000000     1.0   27.7208
1     4.000000     3.0   16.7000
2    47.000000     3.0    9.0000
3     9.000000     3.0   31.3875
4    20.000000     3.0    9.8458
..         ...     ...       ...
707  30.000000     3.0    8.6625
708  26.959410     3.0    8.7125
709  71.000000     1.0   49.5042
710  32.666667     1.0  221.7792
711  49.762895     1.0   25.9250

[712 rows x 3 columns]

In [ ]:
lr = LogisticRegression()
lr.fit(X_train_trf,y_train)
y_pred = lr.predict(X_test_trf)
accuracy_score(y_test,y_pred)

0.7039106145251397

In [ ]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

           Age  Pclass      Fare
0    40.000000     1.0   27.7208
1     4.000000     3.0   16.7000
2    47.000000     3.0    9.0000
3     9.000000     3.0   31.3875
4    20.000000     3.0    9.8458
..         ...     ...       ...
707  30.000000     3.0    8.6625
708  26.959410     3.0    8.7125
709  71.000000     1.0   49.5042
710  32.666667     1.0  221.7792
711  49.762895     1.0   25.9250

[712 rows x 3 columns]

In [ ]:
si = SimpleImputer()
X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [ ]:
lr = LogisticRegression()
lr.fit(X_train_trf2,y_train)
y_pred2 = lr.predict(X_test_trf2)
accuracy_score(y_test,y_pred2)

0.6927374301675978